# Generated by Django 3.1 on 2020-09-21 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0002_employee_email'),
        ('Pickup', '0002_pickup_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickup',
            name='employee_name',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Employee.employee'),
        ),
    ]
