# Generated by Django 3.1 on 2020-09-21 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0001_initial'),
        ('Userproduct', '0002_userproduct_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproduct',
            name='Buyer',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='Buyer.buyer'),
        ),
    ]
