# Generated by Django 3.1.1 on 2020-09-23 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0001_initial'),
        ('Userproduct', '0003_userproduct_buyer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproduct',
            name='Buyer',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='Buyer.buyer'),
        ),
    ]
