# Generated by Django 3.1 on 2020-09-21 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0002_employee_email'),
        ('Cost', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cost',
            name='employee_name',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Employee.employee'),
        ),
    ]
