# Generated by Django 3.1 on 2020-09-21 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Userproduct', '0003_userproduct_buyer'),
        ('Cost', '0002_cost_employee_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cost',
            name='Userproduct',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='Userproduct.userproduct'),
        ),
    ]
